### ISSUE TITLE
Automatic return-based linebreaks instead of “two spaces at end of line” linebreaks

### ISSUE THREAD

**Issue by solitud** [michelf/php-markdown#169] opened 2014-07-14 15:18 UTC
Hi, is there an option to turn on _Automatic return-based linebreaks instead of “two spaces at end of line” linebreaks_ like in the GitHub Markdown parser? If not are there any plans to implement it?

I know this is discussed controversially but I think it would be a huge benefit for vanilla users, and it would help to use Markdown syntax in Forum software etc.

**Comment by standaniels** [comment] 2015-03-02 10:15
Why is this controversially? Could you elaborate, @michelf?

I agree with @solitud, I think `return` character in plain text should create a `<br>` in HTML, because it breaks a line, doesn't it?

**Comment by solitud** [comment] 2015-03-02 11:17
@standaniels: I think it's not in the original specifications.
Anyway, if you dare to mess with the source you find it in _Markdown.php_ line 518:

```
protected function doHardBreaks($text) {
# Do hard breaks:
return preg_replace_callback('/ {2,}\n/', 
array($this, '_doHardBreaks_callback'), $text);
}
```

change to:

```
protected function doHardBreaks($text) {
# Do hard breaks:
return preg_replace_callback('/\n/',
array($this, '_doHardBreaks_callback'), $text);
}
```

**Comment by michelf** [comment] 2015-03-02 11:49
Because that's what the [Markdown Syntax](https://daringfireball.net/projects/markdown/syntax#p) document has to say about line breaks:

> The implication of the "one or more consecutive lines of text" rule is
> that Markdown supports "hard-wrapped" text paragraphs. This differs
> significantly from most other text-to-HTML formatters (including Movable
> Type's "Convert Line Breaks" option) which translate every line break
> character in a paragraph into a `<br />` tag.
> 
> When you _do_ want to insert a `<br />` break tag using Markdown, you
> end a line with two or more spaces, then type return.
> 
> Yes, this takes a tad more effort to create a `<br />`, but a simplistic
> "every line break is a `<br />`" rule wouldn't work for Markdown.
> Markdown's email-style [blockquoting](#blockquote) and multi-paragraph [list items](#list)
> work best -- and look better -- when you format them with hard breaks.

**Comment by standaniels** [comment] 2015-03-02 12:49
Ah, yes, other tags might break when `\n\r` == `<br>`, didn't think of that.

Is t a bug then, that when I want to start a list after a `<br>` it won't be created? For example:

```
Test<space><space>  
1. Option
2. Option
3. Option
```

Results in:

```
<p>Test<br>
1. Option
2. Option
3. Option</p>
```

If so I'll create a new issue for this.

**Comment by michelf** [comment] 2015-03-02 12:56
No, that's a separate thing that has nothing to do with `<br>`. Lists must be separated by a blank line to protect you from making accidental lists with hard-wrapped text:

```
This is a paragraph about the lot number
1. But lot number 2 is better, like number
3. Which lot do you want?
```

The above is not meant to be a list. The blank line is not necessary for sublists.

**Comment by mjau-mjau** [comment] 2016-08-22 06:05
@solitud thanks for your solution to line breaks.

I'm wondering, are there really any downsides to using this fix? I can't seem to think of anything. It's even backwards compatible ... I don't see, from a text-editors perspective, why a line-break should not incur the same result in the rendered output.

**Comment by jcohlmeyer** [comment] 2016-08-26 16:47
Just my opinion, but I think relying on two spaces at the end of a line for a line break is a bit weird and prone to bugs, especially when we have the well established rules for line breaks with \n

Are there downsides to implementing this change mentioned by @solitud that can not be easily worked around, even though it is not sticking to the Markdown spec?

**Comment by jackmcdade** [comment] 2016-08-26 17:03
I see both sides to this. The Markdown spec hasn't changed in 12 years, but the web and authoring tools have changed significantly. That's why we've seen a rise in the popularity of Github Flavored Markdown. 

Unfortunately, there are really no PHP libraries that support GFM completely. I think there is definitely a place for adding a few new conventions here and there. This one in particular relies on invisible characters, which makes it a a weak feature, unless you're using a code editor with invisible character display.

All that to say, I think this solution has merit as a _config_ option perhaps, but not default behavior. That way you get the best of both worlds. Flexibility, and backwards compatibility.

**Comment by michelf** [comment] 2016-08-26 17:07
Note that even the Github Markdown parser has two modes: one where the line breaks are significant and one where you must end the line with two spaces to insert a line break. The first mode is used for comments forms (like here), while the second mode is used for parsing Markdown documents in repositories (like the Readme.md files).

There is no way around the fact that this is _not_ a backward-compatible change: any document with line breaks in it assumes either one or the other behavior from the parser, and if you change the behavior you add or remove line breaks from the document. We could add however a separate mode in PHP Markdown that mirrors more closely Github's comment mode.

**Comment by jackmcdade** [comment] 2016-08-26 17:08
@michelf exactly.

**Comment by mjau-mjau** [comment] 2016-08-26 17:20
@michelf can you explain how it is not backwards compatible?
1. markdown code:
   ![screen1](https://d.pr/i/1ebKM+)
2. render flawless, even if the line-breaks had double-spaces from previous legacy:
   ![screen2](https://d.pr/i/1dUZ3+)

I can only see it's not backwards compatible if someone already went through the pain to use `<br>` tags because it was more convenient than double-spacing. It's certainly backwards compatible with existing pages where double-spaces WERE in fact used ... obviously they have no other effect than exactly that: two empty spaces after some text.

Reading up on the origin of this strange rule, I can't really find anything tangible for the modern age. It seems to be it's there just to prevent the user from using single-line breaks to separate texts, as technically-speaking, it is incorrect from a pure text-writing perspective to have line-breaks without a new paragraph. However, when used to edit web-content, we often need the single line-break to separate links, or just add text below a `<strong>` tag.

**Comment by jackmcdade** [comment] 2016-08-26 17:22
@mjau-mjau If you like to write like _this_...

```
Hello there.
This is how I write sometimes.
It looks good in my editor, and follows my train of thought.
```

And have the output be:

```
Hello there. This is how I write sometimes. It looks good in my editor, and follows my train of thought.
```

You'd be out of luck.

**Comment by mjau-mjau** [comment] 2016-08-26 17:23
@jackmcdade why would you write like that if you didn't want it to appear like that?

**Comment by jackmcdade** [comment] 2016-08-26 17:23
@mjau-mjau It doesn't matter _why_ I would write like that. Right now I _can_ write like that. And if you change the behavior, that's what wouldn't be backwards compatible.

**Comment by mjau-mjau** [comment] 2016-08-26 17:25
if you DO in fact write like that (which I doubt very much), then yes it would render like how you have written it, instead of compiling to a single line.

It's not a good reason.

**Comment by jackmcdade** [comment] 2016-08-26 17:26
There's always someone who does it and has a good reason. I just don't know who they are or what is off the top of my head. Backwards compatibility is backwards compatibility. That's all I'm saying :)

**Comment by mjau-mjau** [comment] 2016-08-26 17:34
I would like to know what that "good reason" could be ...

**Comment by michelf** [comment] 2016-08-26 17:36
The current version of PHP Markdown can parse correctly a document like this one:
https://daringfireball.net/projects/markdown/syntax.text

There is content out there with hard-wrapped plain-text content like that. It's not a rarity. Just look at the unparsed content of Readme files on Github, you'll see plenty.

**Comment by mjau-mjau** [comment] 2016-08-26 17:48
That would be correct. Perhaps I don't see the extent of how php-markdown is being used. When used with any modern CMS / web-editor, I don't see that this would be of any concern whatsoever. People don't write like that (just like they don't write emails like that either), so it would only create an issue when copy-pasting from a source with hard-wrapped text content. Doesn't seem to justify the cause.

Anyway, thanks for all the info. Interesting!

**Comment by jackmcdade** [comment] 2016-08-26 18:01
![image](https://cloud.githubusercontent.com/assets/44739/18015416/a18f9e2e-6b95-11e6-9987-68db7cbe3c5b.png)

**Comment by mjau-mjau** [comment] 2016-08-26 18:13
especially if it's beneficial

**Comment by ljacqu** [comment] 2016-08-26 19:51
For longer blocks of text or more complicated elements I personally think it's a very nice feature to be able to have a line break in the text that won't end up in the resulting document. 

For example, it's convenient to put each "Github badge" that many repos' README have on a new line—as is done on https://github.com/angular/angular/blob/master/README.md; if you go to the Raw view you'll see that each badge is on a new line.

**Comment by jasonvarga** [comment] 2016-08-26 20:42
Throwing my 2 cents in.

I use this extensively. I like to see a block of text and have all the lines end at about the same spot, even if I don't want to render a line break. If I have my editor maximized, I don't want to see a line that goes all the way across my monitor until it wraps (or scrolls).

The following block of text contains newlines purely for editor formatting:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a 
aliquam tortor. Proin sed fringilla velit. Aenean pretium suscipit 
vulputate. Etiam eleifend est sem. Nulla congue varius libero, 
sit amet malesuada nulla. Donec volutpat est sem, convallis 
sollicitudin quam vehicula non. Pellentesque dapibus vitae.
```

The same block of text without the newlines.

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a aliquam tortor. Proin sed fringilla velit. Aenean pretium suscipit vulputate. Etiam eleifend est sem. Nulla congue varius libero, sit amet malesuada nulla. Donec volutpat est sem, convallis sollicitudin quam vehicula non. Pellentesque dapibus vitae.
```

Annoying, right? Similarly, take this HTML:

```
<p>
  <i class="icon left small something" />
  One
  <span class="foo bar baz qux">...</span>
  Two
</p>
```

The browser will show line breaks in the source (who cares) but won't show line breaks in the rendered output. I'm sure everyone has done something like this purely for readability's sake.

Saying all this, I agree that having the _option_ to change the behavior would be useful.

**Comment by jcohlmeyer** [comment] 2016-08-26 22:55
+1 for adding this as an option

**Comment by mjau-mjau** [comment] 2016-08-27 04:54
@jasonvarga I see your argument. However, from the perspective of using markdown in any web/CMS/editor (see screenshot for clarity), this rule becomes incredibly tedious, useless and counter-productive. Should I explain to all users that they need to use double-space to create line-breaks, for (in these cases) absolutely no reason?
![screen1](https://d.pr/i/165rs+)
In these cases, one should **never** try to limit the width of input by hard line-breaks, although that is already quite obvious from the optimized editor (limited by width), and simply because users have evolved from the typewriter era. Why don't they use this markdown-rule for email clients if it's beneficial for the output? Have you ever received an email from someone who uses hard line breaks to limit width? Incredibly annoying, but thankfully incredibly rare these days ...

I see the need to keep things backwards-compatible, but for the sake of improvement for a huge segment of modern-usage scenarios, it certainly would be welcome with an option to disable this debilitating option. It's certainly understandable why markdown and others already implemented it.

**PS!** I know that **php-markdown** is really just a pure conversion of "markdown", so essentially it's not a direct responsibility of this plugin. The php-markdown plugin however, is likely used more in CMS-context than the original markdown-tool was anticipated for.

**Comment by jasonvarga** [comment] 2016-08-27 05:01
I'd say yes, tell your users to use two spaces for a line break. It's markdown. That's how it was designed.

The auto line breaks would not be in accordance with the spec so it should need to be an option you enable if you want it to behave that way.

**Comment by mjau-mjau** [comment] 2016-08-27 05:06
> That's how it was designed.
> The auto line breaks would not be in accordance with the spec

These are non-valid arguments from the perspective of trying to improve upon technologies created a decade ago, now used in modern scenarios. I have already added the fix `return preg_replace_callback('/\n/',`, which works like a dream with no disadvantage whatsoever for a web editor where there is absolutely no reason why anyone would hard-break lines unless it was intended in the output. Benefits hundreds of users on our system.

**Comment by michelf** [comment] 2016-08-27 10:59
If someone is willing to contribute with a pull request: make it an option called `hard_wrap` and I'll be happy to merge (after some testing).

**Comment by jcohlmeyer** [comment] 2016-08-27 17:10
@michelf I will take a fist stab at it today.

This is my first attempted pull request to a php library so any guidance would be most appreciated.

**Comment by jcohlmeyer** [comment] 2016-08-27 17:46
I have created a pull request here: [https://github.com/michelf/php-markdown/pull/244](https://github.com/michelf/php-markdown/pull/244)

I am not sure if I should be writing a test [here](https://github.com/michelf/mdtest) or not, and if so not sure how to go about writing the test.

Any advice / guidance would be most appreciated. Thanks!

**Comment by michelf** [comment] 2016-08-27 18:50
@jcohlmeyer Thank you. It'd be a nice thing to have tests for this, but currently MDTest can't test for anything other than the default settings. There's a lot of options in PHP Markdown that would benefit from having their own test cases, but don't currently. If you, or someone else, want to build the infrastructure for this that would be very welcome. But I know it's a bit much to ask as a condition to accept this small change alone, so I think I'll just merge it after I tested it a bit myself (just give me a day or two).

**Comment by mjau-mjau** [comment] 2016-08-29 04:41
@michelf @jcohlmeyer For the record, I have tested this fix on an existing website with loads of pages of markdown, and the full set of markdown sample rules, and everything remains intact. The line-breaks do not extend inside html tags (unless using `markdown=1`), and neither does the line-break affect other markdown rules (lists etc).

Single line-break = `<br>`
Double line-break = `<p>`
Triple line-break = `<p>`

Seems good to go ...

**Comment by michelf** [comment] 2016-08-29 14:54
So what should happen within list items? Try this thing in a Github comment:

```
paragraph
line2

* item
  line 2
   * subitem
```

And you'll get this:

paragraph
line2
- item
  line 2
  - subitem

So it looks like list items are not affected by the `hard_wrap` options. Although that's not exactly true: list items are affected if they contain a blank line (implying block-level content):

```
* item
  line 2

   * subitem
```
- item
  line 2
  - subitem

**Comment by mjau-mjau** [comment] 2016-08-29 16:29
First, I'm not sure what you are trying to write in your last example. Surely you wouldn't use double line-break if you want to include a child list.

```
* item
  line 2
   * subitem
```

Comes out correctly. Screenshot below, because I don't even know how that can be created with github markdown. Doesn't seem possible ...
![screen](https://d.pr/i/18vcs+)

But, I can see some related issues when lists are immediately followed by a new list. However, this issue seems entirely unrelated the new line-break fix. Here are screenshots:

With the fix implemented, markdown:
![screen1](https://d.pr/i/19yiI+)

Rendered
![screen2](https://d.pr/i/129Vx+)

Ooops, there is a bug. Everything seems to be piled into a single UL.

WITHOUT the new fix (same markdown code as above obv.)
![screen3](https://d.pr/i/DMTJ+)

Rendered
![screen4](https://d.pr/i/c4ML+)

Oops, same bug ... Doesn't seem to be related to the change.

**Comment by michelf** [comment] 2016-08-29 16:59
I'm trying to determine how Github-comment Markdown behaves so as to determine if PHP Markdown's hard-warp mode does the same thing. What I get for this in Github comment:

```
* item
  line 2
   * subitem
```

is this HTML result (copied from the source of this issue page on Github):

```
<ul>
<li>item
line 2

<ul>
<li>subitem</li>
</ul>
</li>
</ul>
```

Clearly there is no `<br/>` there. You can reproduce it by pasting the input above in the comment form and click the preview tab.

I'm leaning towards guessing it's a bug on their end and not something that should be replicated.

**Comment by mjau-mjau** [comment] 2016-08-29 17:11
Hard to say if it's a bug or just intended behavior for no specific reason. My guess would be that it's just not a supported input pattern for Github markdown, eg. using lists with line-breaks within the same list item. It simply doesn't seem possible at all to create this in github-markdown:

![screen](https://d.pr/i/1eYfM+)

But yeh, would be interesting to know if there was a specific reason.

**Comment by mjau-mjau** [comment] 2016-08-29 17:16
My error ... It is possible, but you need to use double-space before the line-break.

It seems perhaps the github-flavored markdown rule only applies in root html element, and defaults to standard markdown when inside other html tags or markdown rules? Kinda makes sense ...

**Comment by michelf** [comment] 2016-08-29 21:06
Ok, so the feature has been merged.

Note that it does hard breaks everywhere, including the content of list items.

**Closed as completed by michelf** 2016-08-29 21:06 UTC

**Comment by mjau-mjau** [comment] 2016-09-05 04:39
Just for reference, a minor issue when using automatic line-breaks with Html `<!-- comments -->`. Since markdown doesn't explicitly recognize html comments, they are treated as normal text, and may result in unwanted `<br>` tags on output.

Not a huge issue, but if you need to add html comments in your markdown, and want to avoid this issue, there are two alternatives:

**1)** Don't add html comments on separate lines.
**2)** Strip away html comments _before_ processing markdown:

``` php
Markdown::defaultTransform(preg_replace('/<!--.*?-->/s', '', $value));
```

**Comment by michelf** [comment] 2016-09-05 10:27
@mjau-mjau Can you file a separate issue to track this? Ideally with some sample input, actual output, and expected output.
