### ISSUE TITLE
Nested ordered list [bug]/[feature]

### ISSUE THREAD

**Issue by isaakengineer** [michelf/php-markdown#312] opened 2018-10-10 00:52 UTC
Code:

```
- Pre-History
	- Year x | Highschool | Web design for online magazine
	- Year x | Middle school | Home made magazine
	- Year x | Primary School | award for school wall magazine & buying kids magazings
- why not
```

Output:

```
<ul>
<li>Pre-History</li>
<li>Year x | Highschool | Web design for online magazine</li>
<li>Year x | Middle school | Home made magazine</li>
<li>Year x | Primary School | award for school wall magazine &amp; buying kids magazings</li>
<li>why not</li>
</ul>
```

Preferred:
 
```
<ul>
<li>Pre-History
  <ul>
    <li>Year x | Highschool | Web design for online magazine</li>
    <li>Year x | Middle school | Home made magazine</li>
    <li>Year x | Primary School | award for school wall magazine &amp; buying kids magazings</li>
  </ul>
</li>
<li>why not</li>
</ul>
```

It's a good package, but sometimes it comes short.

**Comment by alsoNuBe** [comment] 2019-03-06 12:00
My lists were not working at all : line 1056 (which reads '(?:(?<=\n)\n|\A\n?) # Must eat the newline')  was not matching for some reason. When I replaced this with line 1050 (which is simply '^'), then the list worked and I actually got precisely the preferred result above when I pasted in your test text. There is an issue where the first newline after a list is ignored by the parser, but this is easily deal with by inserting two newlines instead of one. I realise that I have effectively made the ($this->list_level) if statement redundant and have not fully examined what all the implications of this would be, but perhaps my 'fix' will help a more proficient coder develop a robust bugfix.
![michelflistoutput](https://user-images.githubusercontent.com/6665630/53879847-65e58480-4007-11e9-801c-0cb8bba2a423.JPG)

**Comment by michelf** [comment] 2019-03-06 12:52
I can't reproduce this problem. If I copy-paste the input on [the dingus](https://michelf.ca/projects/php-markdown/dingus/) it results in a perfectly looking nested list. Could this issue be related to a specific PHP version?

I'd suggest @alsoNuBe try changing the `\A` in the "must read the newline" regex to `^`. Using `^` should have the same effect as `\A` in this regex that has the multiline mode flag "m", but I can't see why replacing the whole thing with `^` would work unless this equivalence is somehow broken.

**Comment by alsoNuBe** [comment] 2019-03-06 14:23
Strange: I have reverted to using the original code in the else part of the if statement (i.e. '(?:(?<=\n)\n|\A\n?)', which I had previously replaced with '^'), and the lists functionality still works as per my previous comment. I have tried in different browsers and after resetting my PC: still works. I have not changed my version of PHP, either. Both versions of the code (with ^ substituting and with (?:(?<=\n)\n|\A\n?)) now seem to give the same (desired) output. I doubt this is a cache issue, as I have tried different browsers and restarted my PC. Anyway - it works for me now.

**Comment by aisbergde** [comment] 2020-05-10 19:07
Please try this to reproduce a nested list issue:

```
nested list:

* topic 1
* topic 2
  * topic 2.1
  * topic 2.2
    * topic 2.2.1
  * topic 2.3

```
in the output topic 2.2.1 is on the same level as topic 2.2, but it should be on the next level

the generated code is

```
<p>nested list:</p>

<ul>
<li>topic 1</li>
<li>topic 2

<ul>
<li>topic 2.1</li>
<li>topic 2.2</li>
<li>topic 2.2.1</li>
<li>topic 2.3</li>
</ul></li>
</ul>

```

**Comment by michelf** [comment] 2020-05-10 19:26
I'll close this bug as I can't reproduce the original poster's problem on [the dingus](https://michelf.ca/projects/php-markdown/dingus/).

@aisbergde: The Markdown syntax says that nested lists need to be indented by 4 spaces or one tab. The way it actually works with this parser (which mimics the original parser's behavior) is that 1 to 4 spaces count as one indent. So your topic 2.2.1 need to be indented by 5 to 8 spaces to count as two levels of indentation.

**Closed as completed by michelf** 2020-05-10 19:26 UTC

**Comment by aisbergde** [comment] 2020-05-11 00:00
Thank you for this answer, this works fine.

Now I have to find a way to tell this to the VS Code plugin "markdown-all-in-one" which generates TOC only with an indent of 2
